/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OpenIE } from "./OpenIE";
export * as factories from "./factories";
export { OpenIE__factory } from "./factories/OpenIE__factory";
